/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafico;



import Entidades.Vendedor;
import Repositorios.CVendedorRepositorio;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author plini
 */
public class JFVendedorCRUD extends javax.swing.JFrame {

    private CVendedorRepositorio _cVendedorRepositorio;
    private String estadoSistema = "guardar";

    public JFVendedorCRUD() {
        initComponents();
        this.setLocationRelativeTo(null);
        _cVendedorRepositorio = new CVendedorRepositorio();

        CargarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        cbGenero = new javax.swing.JComboBox<>();
        cbEstado = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        btnIrComprar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnValidarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Clientes"));
        jPanel1.setAutoscrolls(true);

        jLabel1.setText("Cedula: ");

        txtCedula.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtCedulaInputMethodTextChanged(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCedulaPropertyChange(evt);
            }
        });

        jLabel2.setText("Nombre: ");

        txtNombre.setEnabled(false);

        jLabel3.setText("Genero: ");

        jLabel4.setText("Direccion: ");

        txtDireccion.setEnabled(false);

        jLabel5.setText("Estado: ");

        btnGuardar.setText("Crear Vendedor");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cbGenero.setEnabled(false);

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cbEstado.setEnabled(false);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setEnabled(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnIrComprar.setText("Ir a Compras");
        btnIrComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrComprarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnValidarCliente.setText("Validar Vendedor");
        btnValidarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtDireccion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIrComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnValidarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValidarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrComprar)
                    .addComponent(btnEliminar)))
        );

        tCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarCliente() {
        DefaultTableModel modelCliente = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        ArrayList<Vendedor> listClientes = _cVendedorRepositorio.GetAll();
        String[] clienteString = new String[5];

        modelCliente.addColumn("Cedula");
        modelCliente.addColumn("Nombre");
        modelCliente.addColumn("Direccion");
        modelCliente.addColumn("Genero");
        modelCliente.addColumn("Estado");

        if (listClientes.size() == 0) {
            tCliente.setModel(modelCliente);
            return;
        }

        listClientes.forEach((cliente) -> {
            clienteString[0] = cliente.getCedula();
            clienteString[1] = cliente.getNombre();
            clienteString[2] = cliente.getDireccion();
            clienteString[3] = cliente.getGenero();

            if (cliente.isEstado()) {
                clienteString[4] = "Activo";
            } else {
                clienteString[4] = "Inactivo";
            }
            modelCliente.addRow(clienteString);
        });
        tCliente.setModel(modelCliente);
    }

    private void CrearCliente(Vendedor entidad) {

        try {

            if (_cVendedorRepositorio.Crear(entidad) == 1) {
                JOptionPane.showMessageDialog(null, "Vendedor Creado");
                CargarCliente();
                Limpiar();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error al crear: " + e.getMessage());
            Limpiar();
        }

    }

    private void ModificarCliente(Vendedor entidad) {
        try {

            if (_cVendedorRepositorio.Modificar(entidad) == 1) {
                JOptionPane.showMessageDialog(null, "Cambios realizados");
                CargarCliente();
                Limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al crear: " + e.getMessage());
            Limpiar();
        }
    }

    private void DesactivarCliente(String cedula) {
        try {

            if (_cVendedorRepositorio.Eliminar(cedula) == 1) {
                JOptionPane.showMessageDialog(null, "Vendedor desactivado");
                CargarCliente();
                Limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al crear: " + e.getMessage());
            Limpiar();
        }
    }

    private void Limpiar() {
        txtNombre.setText("");
        txtDireccion.setText("");
        txtCedula.setText("");
        txtCedula.setEnabled(true);
        cbEstado.setSelectedIndex(0);
        cbGenero.setSelectedIndex(0);
        estadoSistema = "guardar";
        btnGuardar.setText("Crear Vendedor");
        btnLimpiar.setText("Limpiar");
        btnEliminar.setEnabled(false);
        DesactivarRegistro();
    }

    private String QuitarGuion(String valor) {
        if (valor == null || valor.isEmpty()) {
            return valor;
        }
        return valor.replace("-", "");
    }

    private String AgregarGuion(String valor) {
        StringBuilder formattedNumber = new StringBuilder(valor);
        formattedNumber.insert(3, '-');
        formattedNumber.insert(11, '-');
        return formattedNumber.toString();
    }

    private void ActivarRegistro() {
        txtNombre.setEnabled(true);
        txtDireccion.setEnabled(true);
        cbGenero.setEnabled(true);
        cbEstado.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        btnValidarCliente.setEnabled(false);
    }

    private void DesactivarRegistro() {
        txtNombre.setEnabled(false);
        txtDireccion.setEnabled(false);
        cbGenero.setEnabled(false);
        cbEstado.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnLimpiar.setEnabled(false);
        btnValidarCliente.setEnabled(true);
    }

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed

    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String Cedula = txtCedula.getText();
        String Nombre = txtNombre.getText();
        String Direccion = txtDireccion.getText();
        String Genero = cbGenero.getSelectedItem().toString();
        String auxEstado = cbEstado.getSelectedItem().toString();
        boolean Estado = false;
        if ("Activo".equals(auxEstado)) {
            Estado = true;
        }

        Vendedor entidad = new Vendedor(Cedula, Nombre, Direccion, Genero, Estado);
        switch (estadoSistema) {
            case "guardar":
                CrearCliente(entidad);
                break;
            case "modificar":
                ModificarCliente(entidad);
                break;
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnIrComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrComprarActionPerformed
        JFPrincipal principal = new JFPrincipal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIrComprarActionPerformed

    private void tClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tClienteMouseClicked
        txtCedula.setEnabled(false);

        int fila = tCliente.getSelectedRow();

        txtCedula.setText(tCliente.getValueAt(fila, 0).toString());
        txtNombre.setText(tCliente.getValueAt(fila, 1).toString());
        txtDireccion.setText(tCliente.getValueAt(fila, 2).toString());
        cbGenero.setSelectedItem(tCliente.getValueAt(fila, 3));
        cbEstado.setSelectedItem(tCliente.getValueAt(fila, 4));

        if ("Activo".equals(tCliente.getValueAt(fila, 4).toString())) {
            btnEliminar.setEnabled(true);
        } else {
            btnEliminar.setEnabled(false);
        }

        btnGuardar.setText("Guardar Cambios");
        estadoSistema = "modificar";
        btnLimpiar.setText("Cancelar");
        ActivarRegistro();
    }//GEN-LAST:event_tClienteMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        estadoSistema = "eliminar";
        DesactivarCliente(txtCedula.getText());

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCedulaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCedulaPropertyChange

    }//GEN-LAST:event_txtCedulaPropertyChange

    private void txtCedulaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtCedulaInputMethodTextChanged
        JOptionPane.showMessageDialog(null, "Error al crear: ");
    }//GEN-LAST:event_txtCedulaInputMethodTextChanged

    private void btnValidarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarClienteActionPerformed

        Vendedor cliente = _cVendedorRepositorio.GetAllEstado(txtCedula.getText());
        if (cliente != null) {
            JOptionPane.showMessageDialog(null, "El Vendedor existe");
            DesactivarRegistro();
            return;
        }
        ActivarRegistro();
    }//GEN-LAST:event_btnValidarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVendedorCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVendedorCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVendedorCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVendedorCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVendedorCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIrComprar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnValidarCliente;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tCliente;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
